/**
 * Argus Core - Spectrogram Viewer Component
 * ==========================================
 * Audio spectrogram visualization with frequency analysis display.
 * 
 * Implements: PRIME_FRONTEND_DOCUMENT.md - Section 2.2 - components/visualization/SpectrogramViewer.tsx
 * 
 * Role: Display mel-spectrogram visualization showing frequency content over time.
 * Helps experts understand where audio anomalies are detected.
 * 
 * Integration:
 * - Used by: AudioAnalysisPanel.tsx
 * - Backend: Uses spectrogram_url from AudioResult, GET /api/v1/analyze/{id}/detail
 *   - Presigned MinIO URL for spectrogram image
 *   - Generated by backend analyzers/audio.py using librosa
 * 
 * Features:
 * - Mel-spectrogram image display
 * - Frequency axis labels (Hz)
 * - Time axis labels (seconds)
 * - Zoom controls for detailed inspection
 * - Color scale legend for amplitude/intensity
 * - Anomaly region highlighting (future)
 * - Playhead position indicator (future)
 * 
 * Component Contract (P0):
 * - Props interface defined
 * - Loading state: Shows skeleton for image loading
 * - Empty state: Shows placeholder when no spectrogram available
 * - Error state: Shows error message with retry option
 * - Accessibility: Alt text, ARIA labels
 * - data-testid: spectrogram-viewer, spectrogram-image, spectrogram-controls
 */

'use client';

import React, { useState, useCallback, useRef } from 'react';
import { cn } from '@/lib/utils';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Slider } from '@/components/ui/slider';
import {
  BarChart3,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  AlertTriangle,
  Download,
  Maximize2,
  Volume2,
  Music,
  Info,
} from 'lucide-react';

// ============== TYPES ==============

/**
 * Props for SpectrogramViewer component
 */
export interface SpectrogramViewerProps {
  /** URL to the spectrogram image (presigned MinIO URL) */
  spectrogramUrl?: string;
  /** Duration of the audio in seconds */
  audioDuration?: number;
  /** Sample rate of the audio (for frequency axis) */
  sampleRate?: number;
  /** Number of mel bands used */
  melBands?: number;
  /** Anomaly time regions [start_ms, end_ms][] */
  anomalyRegions?: [number, number][];
  /** Current playhead position in ms */
  playheadPosition?: number;
  /** Callback when position is clicked */
  onPositionClick?: (ms: number) => void;
  /** Additional CSS classes */
  className?: string;
  /** Compact mode */
  compact?: boolean;
  /** Show header with title */
  showHeader?: boolean;
  /** Custom title */
  title?: string;
}

/**
 * Zoom/pan transform state
 */
interface TransformState {
  scale: number;
  translateX: number;
  translateY: number;
}

// ============== CONSTANTS ==============

const MIN_ZOOM = 1;
const MAX_ZOOM = 4;
const ZOOM_STEP = 0.5;

/**
 * Color scale for spectrogram intensity legend
 * Based on viridis colormap commonly used for spectrograms
 */
const SPECTROGRAM_COLOR_SCALE = [
  { color: '#440154', label: 'Low' },
  { color: '#3b528b', label: '' },
  { color: '#21918c', label: 'Medium' },
  { color: '#5ec962', label: '' },
  { color: '#fde725', label: 'High' },
];

// ============== MAIN COMPONENT ==============

/**
 * SpectrogramViewer Component
 * 
 * Displays a mel-spectrogram visualization of audio content.
 * Useful for identifying vocoder artifacts and spectral anomalies.
 * 
 * @example
 * ```tsx
 * <SpectrogramViewer
 *   spectrogramUrl="https://minio.../spectrogram.png"
 *   audioDuration={15.5}
 *   sampleRate={16000}
 *   melBands={80}
 *   anomalyRegions={[[2000, 3500], [8000, 9200]]}
 * />
 * ```
 */
export function SpectrogramViewer({
  spectrogramUrl,
  audioDuration,
  sampleRate = 16000,
  melBands = 80,
  anomalyRegions = [],
  playheadPosition,
  onPositionClick,
  className,
  compact = false,
  showHeader = true,
  title = 'Mel-Spectrogram Analysis',
}: SpectrogramViewerProps) {
  // ============== STATE ==============

  const [transform, setTransform] = useState<TransformState>({
    scale: 1,
    translateX: 0,
    translateY: 0,
  });
  const [isLoading, setIsLoading] = useState(!!spectrogramUrl);
  const [hasError, setHasError] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const dragStartRef = useRef({ x: 0, y: 0 });
  const containerRef = useRef<HTMLDivElement>(null);

  // ============== HANDLERS ==============

  const handleZoomIn = useCallback(() => {
    setTransform(prev => ({
      ...prev,
      scale: Math.min(prev.scale + ZOOM_STEP, MAX_ZOOM),
    }));
  }, []);

  const handleZoomOut = useCallback(() => {
    setTransform(prev => ({
      ...prev,
      scale: Math.max(prev.scale - ZOOM_STEP, MIN_ZOOM),
    }));
  }, []);

  const handleReset = useCallback(() => {
    setTransform({ scale: 1, translateX: 0, translateY: 0 });
  }, []);

  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    if (transform.scale > 1) {
      setIsDragging(true);
      dragStartRef.current = {
        x: e.clientX - transform.translateX,
        y: e.clientY - transform.translateY,
      };
    }
  }, [transform.scale, transform.translateX, transform.translateY]);

  const handleMouseMove = useCallback((e: React.MouseEvent) => {
    if (isDragging) {
      setTransform(prev => ({
        ...prev,
        translateX: e.clientX - dragStartRef.current.x,
        translateY: e.clientY - dragStartRef.current.y,
      }));
    }
  }, [isDragging]);

  const handleMouseUp = useCallback(() => {
    setIsDragging(false);
  }, []);

  const handleImageLoad = useCallback(() => {
    setIsLoading(false);
    setHasError(false);
  }, []);

  const handleImageError = useCallback(() => {
    setIsLoading(false);
    setHasError(true);
  }, []);

  const handleRetry = useCallback(() => {
    setIsLoading(true);
    setHasError(false);
  }, []);

  const handleContainerClick = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    if (!onPositionClick || !audioDuration || !containerRef.current) return;
    
    const rect = containerRef.current.getBoundingClientRect();
    const relativeX = (e.clientX - rect.left) / rect.width;
    const timeMs = relativeX * audioDuration * 1000;
    onPositionClick(Math.max(0, Math.min(audioDuration * 1000, timeMs)));
  }, [onPositionClick, audioDuration]);

  // ============== EMPTY STATE ==============

  if (!spectrogramUrl) {
    return (
      <EmptySpectrogramViewer 
        className={className} 
        compact={compact}
        showHeader={showHeader}
        title={title}
      />
    );
  }

  // ============== COMPUTED VALUES ==============

  const maxFrequency = sampleRate / 2; // Nyquist frequency
  const playheadPercent = audioDuration && playheadPosition 
    ? (playheadPosition / (audioDuration * 1000)) * 100 
    : undefined;

  // ============== RENDER ==============

  const viewerContent = (
    <div className="space-y-3">
      {/* Controls */}
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Music className="h-4 w-4" aria-hidden="true" />
          <span>{melBands} mel bands</span>
          <span className="text-muted-foreground/50">•</span>
          <span>{(sampleRate / 1000).toFixed(0)} kHz</span>
          {audioDuration && (
            <>
              <span className="text-muted-foreground/50">•</span>
              <span>{audioDuration.toFixed(1)}s</span>
            </>
          )}
        </div>
        
        {/* Zoom controls */}
        <div className="flex items-center gap-1" data-testid="spectrogram-controls">
          <Button
            variant="outline"
            size="icon"
            className="h-8 w-8"
            onClick={handleZoomOut}
            disabled={transform.scale <= MIN_ZOOM}
            aria-label="Zoom out"
          >
            <ZoomOut className="h-4 w-4" />
          </Button>
          <span className="text-xs text-muted-foreground w-12 text-center">
            {Math.round(transform.scale * 100)}%
          </span>
          <Button
            variant="outline"
            size="icon"
            className="h-8 w-8"
            onClick={handleZoomIn}
            disabled={transform.scale >= MAX_ZOOM}
            aria-label="Zoom in"
          >
            <ZoomIn className="h-4 w-4" />
          </Button>
          <Button
            variant="outline"
            size="icon"
            className="h-8 w-8"
            onClick={handleReset}
            disabled={transform.scale === 1 && transform.translateX === 0 && transform.translateY === 0}
            aria-label="Reset zoom"
          >
            <RotateCcw className="h-4 w-4" />
          </Button>
        </div>
      </div>

      {/* Spectrogram Container */}
      <div className="relative">
        {/* Frequency axis label */}
        <div className="absolute -left-2 top-1/2 -translate-y-1/2 -rotate-90 text-xs text-muted-foreground whitespace-nowrap">
          Frequency (Hz)
        </div>
        
        {/* Main image container */}
        <div
          ref={containerRef}
          className={cn(
            'relative overflow-hidden rounded-lg bg-muted/50 ml-4',
            compact ? 'aspect-[4/1]' : 'aspect-[3/1]',
            isDragging ? 'cursor-grabbing' : transform.scale > 1 ? 'cursor-grab' : 'cursor-crosshair'
          )}
          onMouseDown={handleMouseDown}
          onMouseMove={handleMouseMove}
          onMouseUp={handleMouseUp}
          onMouseLeave={handleMouseUp}
          onClick={onPositionClick ? handleContainerClick : undefined}
          data-testid="spectrogram-image"
        >
          {/* Loading state */}
          {isLoading && (
            <div className="absolute inset-0 flex items-center justify-center bg-muted/80 z-10">
              <div className="flex flex-col items-center gap-2">
                <div className="h-8 w-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
                <span className="text-sm text-muted-foreground">Loading spectrogram...</span>
              </div>
            </div>
          )}

          {/* Error state */}
          {hasError && (
            <div className="absolute inset-0 flex items-center justify-center bg-muted z-10">
              <div className="flex flex-col items-center gap-2 text-center p-4">
                <AlertTriangle className="h-10 w-10 text-yellow-500" />
                <p className="text-sm font-medium">Failed to load spectrogram</p>
                <Button variant="outline" size="sm" onClick={handleRetry}>
                  Retry
                </Button>
              </div>
            </div>
          )}

          {/* Spectrogram image */}
          <img
            src={spectrogramUrl}
            alt="Audio mel-spectrogram visualization showing frequency content over time"
            className="absolute inset-0 w-full h-full object-fill"
            style={{
              transform: `scale(${transform.scale}) translate(${transform.translateX / transform.scale}px, ${transform.translateY / transform.scale}px)`,
              transformOrigin: 'center',
            }}
            onLoad={handleImageLoad}
            onError={handleImageError}
            draggable={false}
          />

          {/* Playhead indicator */}
          {playheadPercent !== undefined && (
            <div
              className="absolute top-0 bottom-0 w-0.5 bg-white/80 pointer-events-none"
              style={{ left: `${playheadPercent}%` }}
            />
          )}

          {/* Anomaly region overlays */}
          {audioDuration && anomalyRegions.map(([startMs, endMs], index) => {
            const startPercent = (startMs / (audioDuration * 1000)) * 100;
            const widthPercent = ((endMs - startMs) / (audioDuration * 1000)) * 100;
            
            return (
              <div
                key={index}
                className="absolute top-0 bottom-0 bg-red-500/20 border-l border-r border-red-500/40 pointer-events-none"
                style={{
                  left: `${startPercent}%`,
                  width: `${widthPercent}%`,
                }}
              />
            );
          })}

          {/* Frequency scale overlay (right side) */}
          <div className="absolute right-2 top-2 bottom-2 flex flex-col justify-between text-[10px] text-white/70 font-mono pointer-events-none">
            <span>{(maxFrequency / 1000).toFixed(1)}k</span>
            <span>{(maxFrequency / 2000).toFixed(1)}k</span>
            <span>0</span>
          </div>
        </div>

        {/* Time axis */}
        {audioDuration && (
          <div className="flex justify-between ml-4 mt-1 text-xs text-muted-foreground font-mono">
            <span>0s</span>
            <span>{(audioDuration / 4).toFixed(1)}s</span>
            <span>{(audioDuration / 2).toFixed(1)}s</span>
            <span>{(audioDuration * 3 / 4).toFixed(1)}s</span>
            <span>{audioDuration.toFixed(1)}s</span>
          </div>
        )}
      </div>

      {/* Color scale legend and info */}
      {!compact && (
        <SpectrogramLegend
          anomalyCount={anomalyRegions.length}
          hasAnomalies={anomalyRegions.length > 0}
        />
      )}
    </div>
  );

  // Return with or without header
  if (!showHeader) {
    return (
      <div className={className} data-testid="spectrogram-viewer">
        {viewerContent}
      </div>
    );
  }

  return (
    <Card className={className} data-testid="spectrogram-viewer">
      <CardHeader className={compact ? 'pb-2' : undefined}>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <BarChart3 className="h-5 w-5 text-indigo-500" aria-hidden="true" />
            <CardTitle className={compact ? 'text-base' : 'text-lg'}>
              {title}
            </CardTitle>
          </div>
          {anomalyRegions.length > 0 && (
            <Badge variant="destructive" className="gap-1">
              <AlertTriangle className="h-3 w-3" />
              {anomalyRegions.length} Regions
            </Badge>
          )}
        </div>
        {!compact && (
          <CardDescription>
            Frequency analysis showing audio characteristics over time
          </CardDescription>
        )}
      </CardHeader>
      <CardContent>
        {viewerContent}
      </CardContent>
    </Card>
  );
}

// ============== SUB-COMPONENTS ==============

/**
 * Empty state for spectrogram viewer
 */
function EmptySpectrogramViewer({
  className,
  compact,
  showHeader,
  title,
}: {
  className?: string;
  compact?: boolean;
  showHeader?: boolean;
  title?: string;
}) {
  const content = (
    <div
      className={cn(
        'flex flex-col items-center justify-center rounded-lg border border-dashed bg-muted/30',
        compact ? 'aspect-[4/1] p-4' : 'aspect-[3/1] p-8'
      )}
      data-testid="spectrogram-viewer-empty"
    >
      <BarChart3
        className={cn(
          'text-muted-foreground/40 mb-2',
          compact ? 'h-8 w-8' : 'h-12 w-12'
        )}
        aria-hidden="true"
      />
      <p className={cn(
        'text-muted-foreground font-medium',
        compact && 'text-sm'
      )}>
        No Spectrogram Available
      </p>
      {!compact && (
        <p className="text-sm text-muted-foreground/70 text-center max-w-xs mt-1">
          Audio spectrogram visualization will appear here when audio analysis is complete.
        </p>
      )}
    </div>
  );

  if (!showHeader) {
    return <div className={className}>{content}</div>;
  }

  return (
    <Card className={className}>
      <CardHeader className={compact ? 'pb-2' : undefined}>
        <div className="flex items-center gap-2">
          <BarChart3 className="h-5 w-5 text-indigo-500" aria-hidden="true" />
          <CardTitle className={compact ? 'text-base' : 'text-lg'}>
            {title || 'Mel-Spectrogram Analysis'}
          </CardTitle>
        </div>
      </CardHeader>
      <CardContent>
        {content}
      </CardContent>
    </Card>
  );
}

/**
 * Legend and info for spectrogram
 */
function SpectrogramLegend({
  anomalyCount,
  hasAnomalies,
}: {
  anomalyCount: number;
  hasAnomalies: boolean;
}) {
  return (
    <div
      className="flex flex-wrap items-center justify-between gap-4 p-3 rounded-lg bg-muted/30 border border-dashed"
      data-testid="spectrogram-legend"
    >
      {/* Color scale */}
      <div className="flex items-center gap-2">
        <span className="text-xs text-muted-foreground font-medium">Intensity:</span>
        <div className="flex items-center gap-1">
          <div
            className="h-3 w-24 rounded"
            style={{
              background: `linear-gradient(to right, ${SPECTROGRAM_COLOR_SCALE.map(c => c.color).join(', ')})`,
            }}
          />
        </div>
        <div className="flex items-center gap-3 text-xs text-muted-foreground">
          <span>Low</span>
          <span>High</span>
        </div>
      </div>

      {/* Anomaly indicator */}
      {hasAnomalies && (
        <div className="flex items-center gap-2 text-xs">
          <div className="h-3 w-6 bg-red-500/20 border border-red-500/40 rounded" />
          <span className="text-muted-foreground">
            Anomaly region ({anomalyCount})
          </span>
        </div>
      )}

      {/* Info tooltip */}
      <div className="flex items-center gap-1 text-xs text-muted-foreground">
        <Info className="h-3 w-3" aria-hidden="true" />
        <span>Vocoder artifacts often appear as horizontal bands or spectral gaps</span>
      </div>
    </div>
  );
}

// ============== SKELETON LOADER ==============

/**
 * Skeleton loader for SpectrogramViewer
 */
export function SpectrogramViewerSkeleton({
  className,
  compact = false,
}: {
  className?: string;
  compact?: boolean;
}) {
  return (
    <Card className={className} data-testid="spectrogram-viewer-skeleton">
      <CardHeader className={compact ? 'pb-2' : undefined}>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Skeleton className="h-5 w-5 rounded" />
            <Skeleton className="h-5 w-48" />
          </div>
          <Skeleton className="h-5 w-20" />
        </div>
        {!compact && <Skeleton className="h-4 w-64 mt-2" />}
      </CardHeader>
      <CardContent>
        <div className="space-y-3">
          {/* Controls skeleton */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Skeleton className="h-4 w-24" />
              <Skeleton className="h-4 w-16" />
              <Skeleton className="h-4 w-12" />
            </div>
            <div className="flex gap-1">
              <Skeleton className="h-8 w-8" />
              <Skeleton className="h-8 w-12" />
              <Skeleton className="h-8 w-8" />
              <Skeleton className="h-8 w-8" />
            </div>
          </div>

          {/* Image skeleton */}
          <Skeleton
            className={cn(
              'w-full rounded-lg ml-4',
              compact ? 'aspect-[4/1]' : 'aspect-[3/1]'
            )}
          />

          {/* Time axis skeleton */}
          <div className="flex justify-between ml-4">
            {[1, 2, 3, 4, 5].map((i) => (
              <Skeleton key={i} className="h-3 w-8" />
            ))}
          </div>

          {/* Legend skeleton */}
          {!compact && (
            <Skeleton className="h-12 w-full rounded-lg" />
          )}
        </div>
      </CardContent>
    </Card>
  );
}

// ============== EXPORTS ==============

export default SpectrogramViewer;
